FROM rabbitmq:3.6.12-management

# expose the queue port
EXPOSE 5672

# expose management port
EXPOSE 15672

# Note that we don't ned to specify a command, we can rely on the command form the underlying image!
